"""Fail-closed model discovery for the Home Assistant Needle inference add-on.

Only a manually benchmarked confidence-capable .cact can be activated
automatically. An uncalibrated local LoRA export is never promoted.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Any

MODEL_DIR = Path("/share/needle-training")
APPROVED_ARCHIVE = "approved.cact"
APPROVAL_FILE = "approved.json"
LANGUAGES = ("de", "en", "fr", "es", "it", "nl")
MIN_CONFIDENCE = 0.8


def valid_approval(metadata: Any) -> bool:
    """Check an explicit human-reviewed safety attestation.

    Metadata documents evaluation, not a cryptographic proof of correctness.
    The attestation is intentionally *not* generated by local LoRA training.
    """
    if not isinstance(metadata, dict):
        return False
    if (
        metadata.get("schema_version") != 1
        or metadata.get("model_file") != APPROVED_ARCHIVE
        or metadata.get("confidence_head") != "verified"
        or metadata.get("human_reviewed") is not True
        or metadata.get("confidence_threshold") != MIN_CONFIDENCE
    ):
        return False
    digest = metadata.get("sha256")
    if not isinstance(digest, str) or len(digest) != 64:
        return False
    try:
        int(digest, 16)
    except ValueError:
        return False
    evaluation = metadata.get("evaluation")
    if not isinstance(evaluation, dict):
        return False
    if (
        evaluation.get("unsafe_approvals") != 0
        or evaluation.get("missing_confidence") != 0
        or evaluation.get("transport_errors") != 0
        or evaluation.get("critical_unsafe_approvals") != 0
    ):
        return False
    by_locale = evaluation.get("by_locale")
    if not isinstance(by_locale, dict) or set(by_locale) != set(LANGUAGES):
        return False
    return all(
        isinstance(result, dict)
        and isinstance(result.get("cases"), int)
        and result["cases"] >= 1
        and result.get("unsafe_approvals") == 0
        and result.get("missing_confidence") == 0
        and result.get("transport_errors") == 0
        for result in by_locale.values()
    )


def choose_weights(
    explicit_weights: str,
    auto_trained_weights: bool,
    share_dir: Path = MODEL_DIR,
) -> tuple[str | None, str]:
    """Select existing explicit weights, or a reviewed candidate, or base.

    User-selected explicit weights retain the existing semantics: missing
    configured files are errors, not silent fallbacks.
    """
    if explicit_weights:
        path = Path(explicit_weights)
        if not path.is_absolute():
            raise ValueError(
                "The weights option must be an absolute path (e.g. /share/model.cact)"
            )
        if not path.is_file():
            raise FileNotFoundError(f"Configured weights do not exist: {path}")
        return str(path), "explicit"

    if not auto_trained_weights:
        return None, "base (automatic trained models disabled)"

    candidate = share_dir / APPROVED_ARCHIVE
    approval = share_dir / APPROVAL_FILE
    if not candidate.exists() and not approval.exists():
        # A LoRA .safetensors or uncalibrated .cact is never runnable/eligible.
        return None, "base (no approved trained model found)"
    if not candidate.is_file() or not approval.is_file():
        return None, "base (incomplete trained model approval files)"

    try:
        # Do not permit a symlink outside the dedicated share workspace.
        if candidate.is_symlink() or approval.is_symlink():
            raise ValueError("Symlinked model or approval file")
        metadata = json.loads(approval.read_text(encoding="utf-8"))
        if not valid_approval(metadata):
            raise ValueError("Missing or incomplete calibrated-model attestation")
        with candidate.open("rb") as file:
            digest = hashlib.file_digest(file, "sha256").hexdigest()
        if digest.lower() != metadata["sha256"].lower():
            raise ValueError("Model SHA256 does not match its approval record")
        if candidate.stat().st_size < 1024:
            raise ValueError("Model archive is unexpectedly small")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return None, f"base (trained model rejected: {exc})"
    return str(candidate), "approved trained model (verified checksum and review)"


def main() -> int:
    options_path = Path(os.environ.get("ADDON_OPTIONS", "/data/options.json"))
    try:
        options = (
            json.loads(options_path.read_text(encoding="utf-8"))
            if options_path.exists() else {}
        )
        if not isinstance(options, dict):
            raise ValueError("Options JSON must be an object")
        explicit = options.get("weights", "")
        auto = options.get("auto_trained_weights", True)
        if not isinstance(explicit, str) or type(auto) is not bool:
            raise ValueError("Invalid weights or auto_trained_weights setting")
        weights, reason = choose_weights(
            explicit.strip(),
            auto,
            Path(os.environ.get("TRAINING_SHARE", str(MODEL_DIR))),
        )
        print(f"Needle model selection: {reason}", flush=True)
        # This output is consumed as subprocess stdout; write the path only.
        if weights:
            Path("/tmp/needle-selected-weights").write_text(
                weights, encoding="utf-8"
            )
        else:
            Path("/tmp/needle-selected-weights").unlink(missing_ok=True)
        return 0
    except (OSError, ValueError) as exc:
        print(f"Needle model selection failed: {exc}", flush=True)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
