build_from:
  aarch64: ghcr.io/belphegorprime/boomberman
  amd64: ghcr.io/belphegorprime/boomberman
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Boomberman add-on (Beta)"
  org.opencontainers.image.description: "Boomberman add-on - Beta release candidate version"
  org.opencontainers.image.source: "https://github.com/BelphegorPrime/ha-addon-collection"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"