build_from:
  aarch64: ghcr.io/hassio-addons/base:17.2.4
  amd64: ghcr.io/hassio-addons/base:17.2.4
  armv7: ghcr.io/hassio-addons/base:17.2.4
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Authelia add-on"
  org.opencontainers.image.description: "Authelia add-on"
  org.opencontainers.image.source: "https://github.com/BelphegorPrime/ha-addon-collection"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"
